= パイロット計画・準備・進捗課題確認
:toc:
:toc-title: 目次
:toclevels: 3

== 【実施日】
2025/2/19 9:00-9:30

== 【参加者（敬称略）】
稲村、桐原、木内、山本、酒井、高橋、戸塚、李、相馬

== 【議事内容】
=== 共有事項

=== 2.設計フォーマットパイロット実施準備
**高橋：**
月曜日に話をしたテスト関連やCRUDのファイルをboxの作業フォルダに配置いたしました。

=== 3.環境選定構築
**李：**
spockの検証が終了いたしました。

**李:**
Jacocoの検証をを開始いたしました。
PDFの中でsvgが文字化けするので修正方法を検討中になります。

**高橋：**
以前同様の事象を解消しているため、slackで連携いたします。

桐原さん依頼を追加

=== 4.品質管理
**戸塚：**
成果物事にレビュー方法を検討中

=== 5.その他
.CRUD表
**山本：**
マスタが増えた際にテーブルが横に伸びてしまうため、縦に増やしていくように変更したいが皆様の意見はどうでしょうか。

**高橋：**
頻繁に使用するものでもないためどちらでも問題ないです

**木内：**
いったん山本さん案で進めるで問題ないです

**酒井：**
情報量は同じためどちらでも問題内ですが、マスタチームへの確認が先になると思います。

**山本：**
マスタチームがCRUD表を管理しているのでしょうか。
問い合わせ先をteamsで連絡お願いいたします

**稲村：**
承知いたしました。

.パッケージ案

**山本：**
javaのパッケージ案は下記になります。
[listing]
src
├─controller
│ ├─api
│ ├─batch
│ ├─dto
├─useCase
├─domain
│ ├─order
│ ├─stock
│ ├─allocate
│ ├─shipped
│ ├─valueObject
├─infrastructure
│ ├─repository
│ ├─query
└sql

**李：**
エンティティはどこになりますか

**山本：**
エンティティとモデルが等しいものになります

**高橋：**
後で確認いたします

== 【課題・宿題】
**桐原：**
李さんに文字化けの対処方法をslackで連携する

**稲村：**
CRUD表を管理している方をteamsで山本さんに連携する

**山本：**
CRUD表とパッケージ案のファイルを環境構築フォルダに移したら連絡する

== 【共有】